In [4]:
import csv
import pandas as pd
from random import sample 

df = pd.read_csv('train.csv')

In [5]:
#simple random sampling
no_of_elements = 10
random_index = sample(range(df.shape[0]), no_of_elements)
print(random_index)
print(df.iloc[random_index])

[333, 266, 166, 498, 59, 197, 291, 269, 454, 530]
      Loan_ID  Gender Married Dependents     Education Self_Employed  \
333  LP002101    Male     Yes          0      Graduate           NaN
266  LP001877    Male     Yes          2      Graduate            No
166  LP001577  Female     Yes          0      Graduate            No
498  LP002600    Male     Yes          1      Graduate           Yes
59   LP001199    Male     Yes          2  Not Graduate            No
197  LP001669  Female      No          0  Not Graduate            No
291  LP001938    Male     Yes          2      Graduate            No
269  LP001884  Female      No          1      Graduate            No
454  LP002453    Male      No          0      Graduate           Yes
530  LP002717    Male     Yes          0      Graduate            No

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
333            63337                0.0       490.0             180.0
266             4708             1387.0       150.0             360.0
166             4583                0.0       112.0             360.0
498             2895                0.0        95.0             360.0
59              3357             2859.0       144.0             360.0
197             1907             2365.0       120.0               NaN
291             4400                0.0       127.0             360.0
269             2876             1560.0        90.0             360.0
454             7085                0.0        84.0             360.0
530             1025             5500.0       216.0             360.0

     Credit_History Property_Area Loan_Status
333             1.0         Urban           Y
266             1.0     Semiurban           Y
166             1.0         Rural           N
498             1.0     Semiurban           Y
59              1.0         Urban           Y
197             1.0         Urban           Y
291             0.0     Semiurban           N
269             1.0         Urban           Y
454             1.0     Semiurban           Y
530             NaN         Rural           Y

In [6]:
#systematic sampling
Kth = 10
index = [i for i in range(df.shape[0]) if i%Kth==0]
print(df.iloc[index])

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No
10   LP001024    Male     Yes          2      Graduate            No
20   LP001043    Male     Yes          0  Not Graduate            No
30   LP001091    Male     Yes          1      Graduate           NaN
40   LP001119    Male      No          0      Graduate            No
50   LP001155  Female     Yes          0  Not Graduate            No
60   LP001205    Male     Yes          0      Graduate            No
70   LP001243    Male     Yes          0      Graduate            No
80   LP001265  Female      No          0      Graduate            No
90   LP001316    Male     Yes          0      Graduate            No
100  LP001345    Male     Yes          2  Not Graduate            No
110  LP001385    Male      No          0      Graduate            No
120  LP001426    Male     Yes        NaN      Graduate            No
130  LP001469    Male      No          0      Graduate           Yes
140  LP001497    Male     Yes          2      Graduate            No
150  LP001528    Male      No          0      Graduate            No
160  LP001560    Male     Yes          0  Not Graduate            No
170  LP001581    Male     Yes          0  Not Graduate           NaN
180  LP001633    Male     Yes          1      Graduate            No
190  LP001653    Male      No          0  Not Graduate            No
200  LP001674    Male     Yes          1  Not Graduate            No
210  LP001708  Female      No          0      Graduate            No
220  LP001736    Male     Yes          0      Graduate            No
230  LP001765    Male     Yes          1      Graduate            No
240  LP001798    Male     Yes          2      Graduate            No
250  LP001835    Male     Yes          0  Not Graduate            No
260  LP001865    Male     Yes          1      Graduate            No
270  LP001888  Female      No          0      Graduate            No
280  LP001910    Male      No          1  Not Graduate           Yes
290  LP001936    Male     Yes          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
320  LP002051    Male     Yes          0      Graduate            No
330  LP002097    Male      No          1      Graduate            No
340  LP002115    Male     Yes         3+  Not Graduate            No
350  LP002139    Male     Yes          0      Graduate            No
360  LP002161  Female      No          1      Graduate            No
370  LP002194  Female      No          0      Graduate           Yes
380  LP002226    Male     Yes          0      Graduate           NaN
390  LP002255    Male      No         3+      Graduate            No
400  LP002288    Male     Yes          2  Not Graduate            No
410  LP002318  Female      No          1  Not Graduate           Yes
420  LP002348    Male     Yes          0      Graduate            No
430  LP002377  Female      No          1      Graduate           Yes
440  LP002408    Male      No          0      Graduate            No
450  LP002446    Male     Yes          2  Not Graduate            No
460  LP002478     NaN     Yes          0      Graduate           Yes
470  LP002515    Male     Yes          1      Graduate           Yes
480  LP002534  Female      No          0  Not Graduate            No
490  LP002560    Male      No          0  Not Graduate            No
500  LP002603  Female      No          0      Graduate            No
510  LP002637    Male      No          0  Not Graduate            No
520  LP002689    Male     Yes          2  Not Graduate            No
530  LP002717    Male     Yes          0      Graduate            No
540  LP002741  Female     Yes          1      Graduate            No
550  LP002778    Male     Yes          2      Graduate           Yes
560  LP002807    Male     Yes          2  Not Graduate            No
570  LP002842    Male     Yes          1      Graduate            No
580  LP002892    Male     Yes          2      Graduate            No
590  LP002928    Male     Yes          0      Graduate            No
600  LP002949  Female      No         3+      Graduate           NaN
610  LP002979    Male     Yes         3+      Graduate            No

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
10              3200              700.0        70.0             360.0
20              7660                0.0       104.0             360.0
30              4166             3369.0       201.0             360.0
40              3600                0.0        80.0             360.0
50              1928             1644.0       100.0             360.0
60              2500             3796.0       120.0             360.0
70              3208             3066.0       172.0             360.0
80              3846                0.0       111.0             360.0
90              2958             2900.0       131.0             360.0
100             4288             3263.0       133.0             180.0
110             5316                0.0       136.0             360.0
120             5667             2667.0       180.0             360.0
130            20166                0.0       650.0             480.0
140             5042             2083.0       185.0             360.0
150             6277                0.0       118.0             360.0
160             1863             1041.0        98.0             360.0
170             1820             1769.0        95.0             360.0
180             6400             7250.0       180.0             360.0
190             4885                0.0        48.0             360.0
200             2600             2500.0        90.0             360.0
210            10000                0.0       214.0             360.0
220             2221                0.0        60.0             360.0
230             2491             2054.0       104.0             360.0
240             5819             5000.0       120.0             360.0
250             1668             3890.0       201.0             360.0
260             6083             4250.0       330.0             360.0
270             3237                0.0        30.0             360.0
280             4053             2426.0       158.0             360.0
290             3075             2416.0       139.0             360.0
..               ...                ...         ...               ...
320             2400             2167.0       115.0             360.0
330             4384             1793.0       117.0             360.0
340             2647             1587.0       173.0             360.0
350             9083                0.0       228.0             360.0
360             4723                0.0        81.0             360.0
370            15759                0.0        55.0             360.0
380             3333             2500.0       128.0             360.0
390             9167                0.0       185.0             360.0
400             2889                0.0        45.0             180.0
410             3867                0.0        62.0             360.0
420             5829                0.0       138.0             360.0
430             8624                0.0       150.0             360.0
440             3660             5064.0       187.0             360.0
450             2309             1255.0       125.0             360.0
460             2083             4083.0       160.0             360.0
470             3450             2079.0       162.0             360.0
480             4350                0.0       154.0             360.0
490             2699             2785.0        96.0             360.0
500              645             3683.0       113.0             480.0
510             3598             1287.0       100.0             360.0
520             2192             1742.0        45.0             360.0
530             1025             5500.0       216.0             360.0
540             4608             2845.0       140.0             180.0
550             6633                0.0         NaN             360.0
560             3675              242.0       108.0             360.0
570             3417             1750.0       186.0             360.0
580             6540                0.0       205.0             360.0
590             3000             3416.0        56.0             180.0
600              416            41667.0       350.0             180.0
610             4106                0.0        40.0             180.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
10              1.0         Urban           Y
20              0.0         Urban           N
30              NaN         Urban           N
40              1.0         Urban           N
50              1.0     Semiurban           Y
60              1.0         Urban           Y
70              1.0         Urban           Y
80              1.0     Semiurban           Y
90              1.0     Semiurban           Y
100             1.0         Urban           Y
110             1.0         Urban           Y
120             1.0         Rural           Y
130             NaN         Urban           Y
140             1.0         Rural           N
150             0.0         Rural           N
160             1.0     Semiurban           Y
170             1.0         Rural           Y
180             0.0         Urban           N
190             1.0         Rural           Y
200             1.0     Semiurban           Y
210             1.0     Semiurban           N
220             0.0         Urban           N
230             1.0     Semiurban           Y
240             1.0         Rural           Y
250             0.0     Semiurban           N
260             NaN         Urban           Y
270             1.0         Urban           Y
280             0.0         Urban           N
290             1.0         Rural           Y
..              ...           ...         ...
320             1.0     Semiurban           Y
330             1.0         Urban           Y
340             1.0         Rural           N
350             1.0     Semiurban           Y
360             1.0     Semiurban           N
370             1.0     Semiurban           Y
380             1.0     Semiurban           Y
390             1.0         Rural           Y
400             0.0         Urban           N
410             1.0     Semiurban           N
420             1.0         Rural           Y
430             1.0     Semiurban           Y
440             1.0     Semiurban           Y
450             0.0         Rural           N
460             NaN     Semiurban           Y
470             1.0     Semiurban           Y
480             1.0         Rural           Y
490             NaN     Semiurban           Y
500             1.0         Rural           Y
510             1.0         Rural           N
520             1.0     Semiurban           Y
530             NaN         Rural           Y
540             1.0     Semiurban           Y
550             0.0         Rural           N
560             1.0     Semiurban           Y
570             1.0         Urban           Y
580             1.0     Semiurban           Y
590             1.0     Semiurban           Y
600             NaN         Urban           N
610             1.0         Rural           Y

[62 rows x 13 columns]

In [5]:
#stratified sampling
#stratas formed based on Education
no_of_elements = 4        #number of elements in each strata
unique = list(set(df['Education']))
print('stratas :', unique, '\n')
index_set = [sample(list(df.index[df['Education']==i]), no_of_elements) for i in unique]
index = [j for i in index_set for j in i]
print(df.iloc[index])

stratas : ['Not Graduate', 'Graduate']

      Loan_ID Gender Married Dependents     Education Self_Employed  \
607  LP002964   Male     Yes          2  Not Graduate            No
601  LP002950   Male     Yes          0  Not Graduate           NaN
112  LP001391   Male     Yes          0  Not Graduate            No
107  LP001370   Male      No          0  Not Graduate           NaN
389  LP002250   Male     Yes          0      Graduate            No
77   LP001259   Male     Yes          1      Graduate           Yes
583  LP002898   Male     Yes          1      Graduate            No
514  LP002652   Male      No          0      Graduate            No

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
607             3987             1411.0       157.0             360.0
601             2894             2792.0       155.0             360.0
112             3572             4114.0       152.0               NaN
107             7333                0.0       120.0             360.0
389             5488                0.0       125.0             360.0
77              1000             3022.0       110.0             360.0
583             1880                0.0        61.0             360.0
514             5815             3666.0       311.0             360.0

     Credit_History Property_Area Loan_Status
607             1.0         Rural           Y
601             1.0         Rural           Y
112             0.0         Rural           N
107             1.0         Rural           N
389             1.0         Rural           Y
77              1.0         Urban           N
583             NaN         Rural           N
514             1.0         Rural           N

In [3]:
#cluster sampling
#clusters formed based on number of Dependents
no_of_clusters = 3
unique = list(set(df['Dependents']))
smp = sample(unique, no_of_clusters)
print("clusters :", smp, "selected out of :", unique, '\n')
index_set = [list(df.index[df['Dependents']==i]) for i in smp]
index = [j for i in index_set for j in i]
print(df.iloc[index])

clusters : ['2', '1', nan] selected out of : [nan, '0', '2', '1', '3+']

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
5    LP001011    Male     Yes          2      Graduate           Yes
8    LP001018    Male     Yes          2      Graduate            No
10   LP001024    Male     Yes          2      Graduate            No
11   LP001027    Male     Yes          2      Graduate           NaN
12   LP001028    Male     Yes          2      Graduate            No
14   LP001030    Male     Yes          2      Graduate            No
23   LP001050     NaN     Yes          2  Not Graduate            No
27   LP001073    Male     Yes          2  Not Graduate            No
29   LP001087  Female      No          2      Graduate           NaN
53   LP001179    Male     Yes          2      Graduate            No
55   LP001194    Male     Yes          2      Graduate            No
59   LP001199    Male     Yes          2  Not Graduate            No
71   LP001245    Male     Yes          2  Not Graduate           Yes
82   LP001267  Female     Yes          2      Graduate            No
86   LP001280    Male     Yes          2  Not Graduate            No
91   LP001318    Male     Yes          2      Graduate            No
92   LP001319    Male     Yes          2  Not Graduate            No
100  LP001345    Male     Yes          2  Not Graduate            No
106  LP001369    Male     Yes          2      Graduate            No
108  LP001379    Male     Yes          2      Graduate            No
123  LP001432    Male     Yes          2      Graduate            No
137  LP001491    Male     Yes          2      Graduate           Yes
139  LP001493    Male     Yes          2  Not Graduate            No
140  LP001497    Male     Yes          2      Graduate            No
144  LP001508    Male     Yes          2      Graduate            No
146  LP001516  Female     Yes          2      Graduate            No
153  LP001532    Male     Yes          2  Not Graduate            No
163  LP001570    Male     Yes          2      Graduate            No
169  LP001580    Male     Yes          2      Graduate            No
176  LP001608    Male     Yes          2      Graduate            No
..        ...     ...     ...        ...           ...           ...
463  LP002489  Female      No          1  Not Graduate           NaN
470  LP002515    Male     Yes          1      Graduate           Yes
471  LP002517    Male     Yes          1  Not Graduate            No
478  LP002531    Male     Yes          1      Graduate           Yes
485  LP002544    Male     Yes          1  Not Graduate            No
487  LP002547    Male     Yes          1      Graduate            No
491  LP002562    Male     Yes          1  Not Graduate            No
495  LP002586  Female     Yes          1      Graduate            No
498  LP002600    Male     Yes          1      Graduate           Yes
503  LP002618    Male     Yes          1  Not Graduate            No
509  LP002634  Female      No          1      Graduate            No
511  LP002640    Male     Yes          1      Graduate            No
527  LP002706    Male     Yes          1  Not Graduate            No
528  LP002714    Male      No          1  Not Graduate            No
533  LP002729    Male      No          1      Graduate            No
540  LP002741  Female     Yes          1      Graduate            No
542  LP002753  Female      No          1      Graduate           NaN
543  LP002755    Male     Yes          1  Not Graduate            No
551  LP002784    Male     Yes          1  Not Graduate            No
552  LP002785    Male     Yes          1      Graduate            No
555  LP002792    Male     Yes          1      Graduate            No
561  LP002813  Female     Yes          1      Graduate           Yes
570  LP002842    Male     Yes          1      Graduate            No
578  LP002877    Male     Yes          1      Graduate            No
583  LP002898    Male     Yes          1      Graduate            No
584  LP002911    Male     Yes          1      Graduate            No
585  LP002912    Male     Yes          1      Graduate            No
604  LP002959  Female     Yes          1      Graduate            No
606  LP002961    Male     Yes          1      Graduate            No
611  LP002983    Male     Yes          1      Graduate            No

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
5               5417             4196.0       267.0             360.0
8               4006             1526.0       168.0             360.0
10              3200              700.0        70.0             360.0
11              2500             1840.0       109.0             360.0
12              3073             8106.0       200.0             360.0
14              1299             1086.0        17.0             120.0
23              3365             1917.0       112.0             360.0
27              4226             1040.0       110.0             360.0
29              3750             2083.0       120.0             360.0
53              4616                0.0       134.0             360.0
55              2708             1167.0        97.0             360.0
59              3357             2859.0       144.0             360.0
71              1875             1875.0        97.0             360.0
82              1378             1881.0       167.0             360.0
86              3333             2000.0        99.0             360.0
91              6250             5654.0       188.0             180.0
92              3273             1820.0        81.0             360.0
100             4288             3263.0       133.0             180.0
106            11417             1126.0       225.0             360.0
108             3800             3600.0       216.0             360.0
123             2957                0.0        81.0             360.0
137             3316             3500.0        88.0             360.0
139             4200             1430.0       129.0             360.0
140             5042             2083.0       185.0             360.0
144            11757                0.0       187.0             180.0
146            14866                0.0        70.0             360.0
153             2281                0.0       113.0             360.0
163             4167             1447.0       158.0             360.0
169             8000                0.0       200.0             360.0
176             2045             1619.0       101.0             360.0
..               ...                ...         ...               ...
463             5191                0.0       132.0             360.0
470             3450             2079.0       162.0             360.0
471             2653             1500.0       113.0             180.0
478            16667             2250.0        86.0             360.0
485             1958             2436.0       131.0             360.0
487            18333                0.0       500.0             360.0
491             5333             1131.0       186.0             360.0
495             3326              913.0       105.0              84.0
498             2895                0.0        95.0             360.0
503             4050             5302.0       138.0             360.0
509            13262                0.0        40.0             360.0
511             6065             2004.0       250.0             360.0
527             5285             1430.0       161.0             360.0
528             2679             1302.0        94.0             360.0
533            11250                0.0       196.0             360.0
540             4608             2845.0       140.0             180.0
542             3652                0.0        95.0             360.0
543             2239             2524.0       128.0             360.0
551             2492             2375.0         NaN             360.0
552             3333             3250.0       158.0             360.0
555             5468             1032.0        26.0             360.0
561            19484                0.0       600.0             360.0
570             3417             1750.0       186.0             360.0
578             1782             2232.0       107.0             360.0
583             1880                0.0        61.0             360.0
584             2787             1917.0       146.0             360.0
585             4283             3000.0       172.0              84.0
604            12000                0.0       496.0             360.0
606             3400             2500.0       173.0             360.0
611             8072              240.0       253.0             360.0

     Credit_History Property_Area Loan_Status
5               1.0         Urban           Y
8               1.0         Urban           Y
10              1.0         Urban           Y
11              1.0         Urban           Y
12              1.0         Urban           Y
14              1.0         Urban           Y
23              0.0         Rural           N
27              1.0         Urban           Y
29              1.0     Semiurban           Y
53              1.0         Urban           N
55              1.0     Semiurban           Y
59              1.0         Urban           Y
71              1.0     Semiurban           Y
82              1.0         Urban           N
86              NaN     Semiurban           Y
91              1.0     Semiurban           Y
92              1.0         Urban           Y
100             1.0         Urban           Y
106             1.0         Urban           Y
108             0.0         Urban           N
123             1.0     Semiurban           Y
137             1.0         Urban           Y
139             1.0         Rural           N
140             1.0         Rural           N
144             1.0         Urban           Y
146             1.0         Urban           Y
153             1.0         Rural           N
163             1.0         Rural           Y
169             1.0     Semiurban           Y
176             1.0         Rural           Y
..              ...           ...         ...
463             1.0     Semiurban           Y
470             1.0     Semiurban           Y
471             0.0         Rural           N
478             1.0     Semiurban           Y
485             1.0         Rural           Y
487             1.0         Urban           N
491             NaN         Urban           Y
495             1.0     Semiurban           Y
498             1.0     Semiurban           Y
503             NaN         Rural           N
509             1.0         Urban           Y
511             1.0     Semiurban           Y
527             0.0     Semiurban           Y
528             1.0     Semiurban           Y
533             NaN     Semiurban           N
540             1.0     Semiurban           Y
542             1.0     Semiurban           Y
543             1.0         Urban           Y
551             1.0         Rural           Y
552             1.0         Urban           Y
555             1.0     Semiurban           Y
561             1.0     Semiurban           Y
570             1.0         Urban           Y
578             1.0         Rural           Y
583             NaN         Rural           N
584             0.0         Rural           N
585             1.0         Rural           N
604             1.0     Semiurban           Y
606             1.0     Semiurban           Y
611             1.0         Urban           Y

[203 rows x 13 columns]